# Generated by Django 5.2.7 on 2025-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung của thông báo. Có thể sử dụng HTML.')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', help_text='Kiểu thông báo (ảnh hưởng đến màu sắc).', max_length=10)),
                ('link', models.URLField(blank=True, help_text='(Tùy chọn) Một liên kết mà người dùng có thể nhấp vào.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ những thông báo được kích hoạt mới được hiển thị.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
