# Generated by Django 5.2.7 on 2025-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_claps_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Attachment/Image'),
        ),
    ]
