# Generated by Django 5.2.7 on 2025-11-16 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_parent_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clapped_by',
            field=models.ManyToManyField(blank=True, related_name='clapped_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
